### ISSUE TITLE
d3 bindings

### ISSUE THREAD

**Issue by kindlychung** [mathieuleclaire/scaladget#2]
How do you compare the d3 bindings of this repo to the other two out there?

https://github.com/spaced/scala-js-d3
https://github.com/greencatsoft/scalajs-d3

**Comment by mathieuleclaire** [comment]
I guess, they are equivalent. When I started with this binding, there were no wrapper for d3. Feel free to try it ! You can find an example here https://github.com/mathieuleclaire/scalaWUI/blob/master/client/src/main/scala/fr/iscpif/client/FlowChart.scala. It reproduces this D3 example: http://bl.ocks.org/cjrd/6863459 in a reactive manner.

**Comment by kindlychung** [comment]
Cool. Thanks!
