### ISSUE TITLE
select is not a function

### ISSUE THREAD

**Issue by kindlychung** [mathieuleclaire/scaladget#3]
In this toy project:

https://github.com/kindlychung/learnd3/blob/master/src/main/scala/tutorial/webapp/LearnD3.scala#L19

I am getting this error from the browser:

```
Uncaught TypeError: $g.d3.select is not a function
$c_Ltutorial_webapp_LearnD3$.main__Lorg_scalajs_dom_raw_HTMLDivElement__V @ LearnD3.scala:19
$c_Ltutorial_webapp_LearnD3$.$$js$exported$meth$main__Lorg_scalajs_dom_raw_HTMLDivElement__O @ LearnD3.scala:14
$c_Ltutorial_webapp_LearnD3$.main @ LearnD3.scala:14(anonymous function) @ index-dev.html:28
workbench.js:61
Loading Workbench
```

Any idea what went wrong? Thanks!

**Comment by kindlychung** [comment]
Ok, this is resolved by: 

```
jsDependencies += "org.webjars" % "d3js" % "3.5.6" / "d3.min.js"
```
 in `build.sbt`.

**Comment by mathieuleclaire** [comment]
I prefer not to set a js dependency in scaladget, so that the wrapping does not depend on the D3 versions. But you can indeed add this dependency in your project.
